### ISSUE TITLE
Play button

### ISSUE THREAD

**Issue by majacannavo** [csci312-s21/project-amber-ayeaye#37]
As a Listener, I want an easy way to play the radio livestream with the simple click of a button.

ClassName: PlayButton

Responsibilities: Connects to the boombox wrmc link that plays the livestream. Uses <iframe> html tag, like professor Andrews suggested. Plays only the sound.

**Comment by brendanphilbin** [comment]
As a listener, I would like to be able to listen to the radio station live without navigating away from the homepage so that I can continue exploring the radio station without interrupting my listening experience.

Class Name
Player

Responsibilities
Output audio from embedded livestream
Controls the volume of the livestream
Allows the user to pause the livestream

Collaborators
None

Acceptance criteria: clicking play/pause button plays/pauses audio and does not open up a new tab/window

Difficulty Score: 2
